// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfitxmgdvqieacjjbsiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmaXR4bWdkdnFpZWFjampic2l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjcyMzgsImV4cCI6MjA2NDIwMzIzOH0.fTH0tSO_8A5mU9LiGnA4yvYKsVxV-FuopJVbFrQ86PQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);