// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovucbxiujkuassdeuaqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92dWNieGl1amt1YXNzZGV1YXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTE1OTgsImV4cCI6MjA2OTQ2NzU5OH0.mmgkRKDh90KQdktRMdrFIcQf3JRUhzKLKhZDudI0hlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});